In [2]:
arr = [1,2,3,4]

arr[0]

1

In [9]:
import numpy as np
a = np.array([1,2,3])
a * 4

array([ 4,  8, 12])

In [ ]:
arr = ["Sandeep", 123, 4.5, True, (1,2,3), [6,7]]

for num in arr:
    print(num)
    print("---")
print("***************")

Sandeep
---
123
---
4.5
---
True
---
(1, 2, 3)
---
[6, 7]
---
***************


In [10]:
a = "sandeep"
a * 4

'sandeepsandeepsandeepsandeep'

In [11]:
for i in "sandeep":
    print(i)

s
a
n
d
e
e
p


In [12]:
[1,2]*4

[1, 2, 1, 2, 1, 2, 1, 2]

In [14]:
import numpy as np 

arr = np.array([-5, 1, -2, 8])
print(arr - -5)
(arr - (-5))/(8 - (-5))


[ 0  6  3 13]


array([0.        , 0.46153846, 0.23076923, 1.        ])

In [17]:
arr = np.array([4,5,6])

np.mean(arr)

np.float64(5.0)

In [ ]:
# standard deviation?
dataset1 = [1, 1.1, .9]
dataset2 = [1, -5, 10] 

# Which dataset is has more variance? 
# Come up with a number representing variance

# subtract each number from mean, take the square, sum it up and divide by counts. -> variance

# take the variance -> square root -> standard deviation

np.std(dataset1), np.std(dataset2)

(np.float64(0.08164965809277262), np.float64(6.164414002968976))

In [19]:
# Can you do it in 2D?

def compute_mean(numbers):
    sm = 0
    counts = 0
    for i in numbers:
        sm += i 
        counts += 1
    return sm / counts

from math import sqrt
def compute_sd(numbers):
    mu = compute_mean(numbers)
    sd = 0
    var = 0
    n = len(numbers)
    for i in numbers:
        var += (i-mu)**2
        #sd = sd+compute_mean(abs(sd1))
    sd = sqrt(var/n)
    return sd
#compute_sd([0, 100, 0, 100, 50])
compute_sd([10, 12, 12, 13, 12, 11, 90])

27.42485093814717

In [20]:
compute_sd(dataset1), compute_sd(dataset2)

(0.08164965809277262, 6.164414002968976)

In [ ]:
ds1 = [0, 10, 9, 9]
ds2 = [0, 10, 9, 4]

In [21]:
dataset = np.array([.1, .11, 10000000000, 2000000000])
m, mx = np.min(dataset), np.max(dataset)
(dataset - m )/(mx - m)


array([0.e+00, 1.e-12, 1.e+00, 2.e-01])

In [22]:
ds = np.array([1, 2, 3, 5, 4, 4])
np.std(ds)


np.float64(1.3437096247164249)

In [24]:
ds1 = np.array([1, 2, 3, 5, 4, 4, 100])
np.std(ds1)


np.float64(33.90743702662125)

In [37]:
mean = np.mean(ds1)
mean

# Z-Score 
ds1 - mean/np.std(ds1)

array([ 0.49863506,  1.49863506,  2.49863506,  4.49863506,  3.49863506,
        3.49863506, 99.49863506])

In [39]:
arr = np.array([1,2,3, 1, 2, 4, 1, 1, 1, 1, 1, 1])
# mean 
np.sum(arr)/len(arr)

np.float64(1.5833333333333333)

In [ ]:
# mode
1 

In [44]:
# median
arr = np.array([1,2,3, 1, 2, 4, 8, 10, 11, 21, 31, 41])
arr.sort()
arr 

array([ 1,  1,  2,  2,  3,  4,  8, 10, 11, 21, 31, 41])

In [43]:
len(arr)

12

In [46]:
arr = [1,2,3,4,5,6,700]
np.mean(arr), arr[3]

(np.float64(103.0), 4)